# Bronze Layer — Drug Delivery Dataset (Master_Sheet)
---
**Objective:** Read and save the raw `Master_Sheet` data exactly as is, without any modification (no cleaning, no renaming, no standardization).

**Environment:** Google Colab

**Input:** `Drug_Delivery_Dataset.xlsx` -> Sheet: `Master_Sheet`

**Output:** `Bronze_Layer/DrugDelivery_Bronze.csv`

## Connect Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. Imports & Setup

In [ ]:
#1. Install necessary libraries
import subprocess
subprocess.run(["pip", "install", "openpyxl", "--quiet"])

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import os

os.makedirs("Bronze_Layer", exist_ok=True)
print("Libraries imported | Bronze_Layer folder ready")

Libraries imported | Bronze_Layer folder ready

In [ ]:
# 2. Configure pandas display settings
pd.options.display.max_rows = None
pd.options.display.max_columns = None

## 2. Load Raw Data — Master_Sheet

In [ ]:
# 3. Load the raw Excel file -> Master_Sheet only
# If uploaded directly to Colab session:
file_path = "/content/drive/MyDrive/Drug Delivery Project/1- Medallion Architecture/1- Bronze/Drug_Delivery_Dataset.xlsx"
# If stored on Google Drive, use the full path instead, e.g.:
# file_path = "/content/drive/MyDrive/<your_folder>/Drug_Delivery_Dataset.xlsx"

df_bronze = pd.read_excel(file_path, sheet_name="Master_Sheet")

print(f"Shape: {df_bronze.shape[0]:,} rows | {df_bronze.shape[1]} columns")
df_bronze.head(3)

Shape: 2,374 rows | 27 columns

,NPs ID,NP_Class,INPs_Core,Targeting Strategy,Shape,PDI,Size (nm),Size_Category,Zeta Potential (mv),Zeta_Category,Responsive release,Tumor Cell,Tumor Site,Tumor Size ( mm³),Administration Dosages (mg/kg),Organ or tissue,Time point (h),Biodistribution (%ID),Tumor_%ID,Liver_%ID,Tumor selectivity,Selectivity_Index,Targeting_Efficiency,Shell Type,MW Shell,HAS_PEG,Spleen_%ID
0,INPs-P1,Inorganic,Gold,Active,Rod,NaN,37.5,Optimal Range,-18.0,Negative,No,HeLa cell,Cervix,100.0,20.0,Tumor,6.0,1.64,1.64,29.03,NaN,0.051589,Moderate,PEG,4441,Yes,2.76
1,INPs-P1,Inorganic,Gold,Active,Rod,NaN,37.5,Optimal Range,-18.0,Negative,No,HeLa cell,Cervix,100.0,20.0,Tumor,24.0,2.06,2.06,31.70,NaN,0.059281,Moderate,PEG,4441,Yes,3.05
2,INPs-P1,Inorganic,Gold,Active,Rod,NaN,37.5,Optimal Range,-18.0,Negative,No,HeLa cell,Cervix,100.0,20.0,Tumor,168.0,2.01,2.01,21.74,NaN,0.083024,Moderate,PEG,4441,Yes,2.47

## 3. Column Overview

In [ ]:
print("Columns")
print(df_bronze.columns.tolist())

Columns
['NPs ID', 'NP_Class', 'INPs_Core', 'Targeting Strategy', 'Shape', 'PDI', 'Size (nm)', 'Size_Category', 'Zeta Potential (mv)', ' Zeta_Category', 'Responsive release', 'Tumor Cell', 'Tumor Site', 'Tumor Size ( mm³)', 'Administration Dosages (mg/kg)', 'Organ or tissue', 'Time point (h)', 'Biodistribution (%ID)', 'Tumor_%ID', 'Liver_%ID', 'Tumor selectivity', 'Selectivity_Index', 'Targeting_Efficiency', 'Shell Type', 'MW Shell', 'HAS_PEG', 'Spleen_%ID']

In [ ]:
print("Data Types")
print(df_bronze.dtypes.to_string())

Data Types
NPs ID                             object
NP_Class                           object
INPs_Core                          object
Targeting Strategy                 object
Shape                              object
PDI                               float64
Size (nm)                         float64
Size_Category                      object
Zeta Potential (mv)               float64
 Zeta_Category                     object
Responsive release                 object
Tumor Cell                         object
Tumor Site                         object
Tumor Size ( mm³)                 float64
Administration Dosages (mg/kg)    float64
Organ or tissue                    object
Time point (h)                    float64
Biodistribution (%ID)             float64
Tumor_%ID                         float64
Liver_%ID                         float64
Tumor selectivity                 float64
Selectivity_Index                 float64
Targeting_Efficiency               object
Shell Type                         object
MW Shell                           object
HAS_PEG                            object
Spleen_%ID                        float64

In [ ]:
#Data Info
df_bronze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2374 entries, 0 to 2373
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NPs ID                          2374 non-null   object
 1   NP_Class                        2374 non-null   object
 2   INPs_Core                       1375 non-null   object
 3   Targeting Strategy              2374 non-null   object
 4   Shape                           2374 non-null   object
 5   PDI                             1002 non-null   float64
 6   Size (nm)                       2374 non-null   float64
 7   Size_Category                   2374 non-null   object
 8   Zeta Potential (mv)             1763 non-null   float64
 9    Zeta_Category                  1763 non-null   object
 10  Responsive release              2374 non-null   object
 11  Tumor Cell                      2374 non-null   object
 12  Tumor Site                      2374 non-null   object
 13  Tumor Size ( mm³)               2172 non-null   float64
 14  Administration Dosages (mg/kg)  2119 non-null   float64
 15  Organ or tissue                 2374 non-null   object
 16  Time point (h)                  2374 non-null   float64
 17  Biodistribution (%ID)           2374 non-null   float64
 18  Tumor_%ID                       2374 non-null   float64
 19  Liver_%ID                       2374 non-null   float64
 20  Tumor selectivity               1728 non-null   float64
 21  Selectivity_Index               2374 non-null   float64
 22  Targeting_Efficiency            2374 non-null   object
 23  Shell Type                      2374 non-null   object
 24  MW Shell                        2374 non-null   object
 25  HAS_PEG                         2374 non-null   object
 26  Spleen_%ID                      2374 non-null   float64
dtypes: float64(12), object(15)
memory usage: 500.9+ KB

In [ ]:
#Data Description
df_bronze.describe()

,PDI,Size (nm),Zeta Potential (mv),Tumor Size ( mm³),Administration Dosages (mg/kg),Time point (h),Biodistribution (%ID),Tumor_%ID,Liver_%ID,Tumor selectivity,Selectivity_Index,Spleen_%ID
count,1002.000000,2374.000000,1763.000000,2172.000000,2.119000e+03,2374.000000,2374.000000,2374.000000,2374.000000,1728.000000,2374.000000,2374.000000
mean,0.347335,74.980181,-8.233137,469.668508,1.236877e+01,19.188987,5.125343,1.314913,17.160596,0.459491,0.297319,2.299157
std,0.509322,60.572951,13.010360,966.513879,2.238192e+01,35.204207,11.855162,2.376916,19.215821,0.498501,0.874150,6.868356
min,0.020000,1.400000,-43.000000,50.000000,1.350000e-09,0.000000,0.000600,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.120000,18.000000,-19.600000,100.000000,3.750000e+00,2.000000,0.190000,0.190530,2.905000,0.000000,0.019660,0.150000
50%,0.200000,64.210000,-4.000000,100.000000,5.000000e+00,6.000000,0.691596,0.520000,9.478712,0.000000,0.054184,0.456985
75%,0.200000,110.000000,0.000000,270.000000,1.100000e+01,24.000000,3.680000,1.280000,24.281486,1.000000,0.137494,1.720000
max,1.900000,225.200000,18.700000,4170.000000,1.800000e+02,336.000000,95.070000,22.280000,93.640000,1.000000,7.223684,95.070000

## 4. Save Bronze Layer

In [ ]:
#Save data as CSV in Bronze file (Data As Is)
df_bronze.to_csv("Bronze_Layer/DrugDelivery_Bronze.csv", index=False)

print(f"Saved: Bronze_Layer/DrugDelivery_Bronze.csv")
print(f"Rows: {df_bronze.shape[0]:,} | Columns: {df_bronze.shape[1]}")

Saved: Bronze_Layer/DrugDelivery_Bronze.csv
Rows: 2,374 | Columns: 27